import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
const quality=JSON.parse(readFileSync('data/transfermarkt/data-quality.json','utf8'));
const pool=JSON.parse(readFileSync('app/data/auction-pool.generated.json','utf8'));
test('source database and generated pool pass integrity thresholds',()=>{const db=new DatabaseSync('data/transfermarkt/players.sqlite',{readOnly:true});assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(db.prepare('SELECT COUNT(*) count FROM players').get().count,quality.sourceRows);assert.ok(Number(db.prepare("SELECT COUNT(*) count FROM players WHERE auction_slot='RW'").get().count)>1000);assert.ok(Number(db.prepare("SELECT COUNT(*) count FROM players WHERE auction_slot='LW'").get().count)>1000);db.close();assert.ok(quality.sourceRows>=10000);assert.ok(quality.playableProfiles>=1000);assert.ok(quality.wingMappings.right>1000);assert.ok(quality.wingMappings.left>1000)});
test('every era, role and rating tier can support eight managers plus surprise lot',()=>{for(const era of ['current','legends'])for(const [slot,players] of Object.entries(pool[era])){assert.ok((players as unknown[]).length>=9,`${era}/${slot}`);for(const p of players as Array<{rating:number;price:number;name:string}>){assert.ok(p.name);assert.ok(p.rating>=0&&p.rating<=100);assert.ok(p.price>=5)}}});
test('responsive rules cover tablet and mobile layouts',()=>{const css=readFileSync('app/globals.css','utf8');assert.match(css,/@media\(max-width:1024px\)/);assert.match(css,/@media\(max-width:720px\)/);assert.match(css,/@media\(max-width:640px\)/)});
test('formation places AM behind the striker and DM/CM side by side',()=>{const page=readFileSync('app/page.tsx','utf8'),online=readFileSync('app/online/page.tsx','utf8');assert.match(page,/DM:\{left:'36%',top:'55%'\}, CM:\{left:'64%',top:'55%'\}, AM:\{left:'50%',top:'30%'\}/);assert.match(online,/DM:\{left:'36%',top:'57%'\},CM:\{left:'64%',top:'57%'\},AM:\{left:'50%',top:'32%'\}/)});
test('local and multiplayer modes share the root page',()=>{const page=readFileSync('app/page.tsx','utf8'),online=readFileSync('app/online/page.tsx','utf8');assert.match(page,/mode==='online'\?<OnlineGame/);assert.match(online,/location\.replace\(`\/\?\$\{params\.toString\(\)\}`\)/);assert.doesNotMatch(online,/location\.origin\}\/online\?room=/)});
test('multiplayer setup exposes all six pool tiers',()=>{const online=readFileSync('app/online/page.tsx','utf8');assert.match(online,/Havuza dahil edilecek seviyeler/);assert.match(online,/RATING_TIERS\.map\(tier/);assert.match(online,/settings\.selectedTiers\.length\}\/6 seviye seçili/)});
test('bench mode and mobile manager navigation are exposed in both game modes',()=>{const page=readFileSync('app/page.tsx','utf8'),online=readFileSync('app/online/page.tsx','utf8'),rooms=readFileSync('lib/rooms.ts','utf8'),css=readFileSync('app/globals.css','utf8');assert.match(page,/4 yedek olsun/);assert.match(page,/includeBench\?250:0/);assert.match(online,/Açık artırma gidişatı/);assert.match(online,/Kadrom/);assert.match(online,/includeBench:true/);assert.match(rooms,/includeBench\?250:0/);assert.match(css,/\.manager-view-tabs\{position:fixed/)});
test('auction progress notes include player names and the defensive midfielder label is explicit',()=>{const page=readFileSync('app/page.tsx','utf8'),online=readFileSync('app/online/page.tsx','utf8'),engine=readFileSync('lib/game-engine.ts','utf8');assert.match(page,/Savunmacı Merkez Orta Saha/);assert.match(page,/auctionProgressLabel\(pool,index\)/);assert.match(online,/auctionProgressLabel\(game\.pool,game\.index\)/);assert.match(engine,/pozisyonu için \$\{ordinal\}\. oyuncu: \$\{lot\.name\}/)});

