import test from 'node:test';import assert from 'node:assert/strict';
import {affordableLimit,auctionOpeningPrice,auctionPassIsSafe,calculateStartingBudget,canPlaceBid,canPlaceLotBid,hashSeed,openingPrice,passIsSafe,preferFresh,rankManagers,safeCsvCell,scoreManager,seededRandom,shuffleSeeded,validManagerNames,type Footballer,type Manager,type Slot} from '../lib/game-engine.ts';
import {COACHES} from '../lib/coaches.ts';
const slots:Slot[]=['GK','RB','CB1','CB2','LB','DM','CM','AM','RW','LW','ST'];
const player=(slot:Slot,rating=85,price=50,i=0):Footballer=>({id:`${slot}-${i}`,name:`P${i}`,slot,role:slot,rating,price,nation:'TR'});
test('seeded shuffle is reproducible and preserves members',()=>{const a=shuffleSeeded([1,2,3,4,5],seededRandom(hashSeed('game-1')));const b=shuffleSeeded([1,2,3,4,5],seededRandom(hashSeed('game-1')));assert.deepEqual(a,b);assert.deepEqual([...a].sort(),[1,2,3,4,5])});
test('reserve protects the remaining squad slots and a coach budget',()=>{const m:Manager={id:0,name:'A',budget:100,squad:{GK:player('GK')},spent:0};assert.equal(affordableLimit(m),50)});
test('opening price adapts to what managers can safely afford',()=>{const lot=player('ST',90,120);const ms:Manager[]=[{id:0,name:'A',budget:60,squad:{},spent:0},{id:1,name:'B',budget:80,squad:{},spent:0}];assert.equal(openingPrice(lot,ms),25)});
test('every eligible room manager can place a live bid',()=>{const lot=player('ST',90,25),guest:Manager={id:1,name:'Guest',budget:100,squad:{},spent:0};assert.equal(canPlaceBid(guest,lot,25,1),true);assert.equal(canPlaceBid(guest,lot,25,1,[1]),false);guest.squad.ST=lot;assert.equal(canPlaceBid(guest,lot,25,1),false)});
test('pass is disabled on the last safe candidate',()=>{const pool=[player('GK',80,20,1),player('GK',80,20,2)];const ms:Manager[]=[{id:0,name:'A',budget:100,squad:{},spent:0},{id:1,name:'B',budget:100,squad:{},spent:0}];assert.equal(passIsSafe(pool,0,ms),false);pool.push(player('GK',80,20,3));assert.equal(passIsSafe(pool,0,ms),true)});
test('every simulated manager can finish eleven slots without negative budget',()=>{for(let run=0;run<1000;run++){const budget=300;const ms:Array<Manager>=Array.from({length:2},(_,id)=>({id,name:`M${id}`,budget,squad:{},spent:0}));for(const slot of slots)for(const m of ms){const p=player(slot,75+run%20,5,run);m.squad[slot]=p;m.budget-=p.price;m.spent+=p.price}assert.equal(Object.keys(ms[0].squad).length,11);assert.ok(ms.every(m=>m.budget>=0))}});
test('score ranking uses hundredth precision and deterministic tie breakers',()=>{const squad=Object.fromEntries(slots.map((s,i)=>[s,player(s,80+i%3,5,i)]));const ranked=rankManagers([{id:0,name:'A',budget:100,squad,spent:55},{id:1,name:'B',budget:90,squad:{...squad,ST:player('ST',90)},spent:65}]);assert.equal(ranked[0].name,'B');assert.equal(Number.isInteger(ranked[0].score*100),true)});
test('names and CSV cells are hardened',()=>{assert.equal(validManagerNames(['Yasin',' yasin ']),false);assert.equal(validManagerNames(['','Yakup']),false);assert.match(safeCsvCell('=1+1'),/^"'/)});
test('all-mode budget stays below one billion',()=>{const pool=slots.flatMap(s=>[player(s,80,30),player(s,82,40,1)]);assert.ok(calculateStartingBudget(pool,'all')<1000);assert.equal(calculateStartingBudget(pool,'best'),1000)});
test('recent lots are avoided until fresh candidates run out',()=>{const candidates=['a','b','c','d'].map(id=>({id})),random=seededRandom(hashSeed('fresh'));const selected=preferFresh(candidates,new Set(['a','b']),3,random);assert.equal(selected.filter(x=>x.id==='a'||x.id==='b').length,1);assert.deepEqual(new Set(selected.map(x=>x.id)),new Set(['c','d',selected.find(x=>x.id==='a'||x.id==='b')!.id]))});
test('coach auction uses remaining budget and prevents duplicate coaches',()=>{const coach=COACHES[0],manager:Manager={id:0,name:'A',budget:45,squad:{},spent:0};assert.equal(auctionOpeningPrice(coach,[manager]),coach.price);assert.equal(canPlaceLotBid(manager,coach,coach.price,0),true);assert.equal(auctionPassIsSafe([coach,COACHES[1]],0,[manager]),true);manager.coach=coach;assert.equal(canPlaceLotBid(manager,COACHES[1],5,0),false)});
test('a compatible coach can only add a positive team contribution',()=>{const squad=Object.fromEntries(slots.map((slot,i)=>[slot,player(slot,86+i%4,10,i)]));const base:Manager={id:0,name:'A',budget:100,squad,spent:110},withCoach:Manager={...base,budget:60,coach:COACHES.find(c=>c.preferredFormation==='4-2-3-1')};const plain=scoreManager(base),coached=scoreManager(withCoach);assert.ok(coached.coachBoost>0);assert.ok(coached.score>plain.score);assert.ok(coached.coachFit>=0)});

