import {env} from 'cloudflare:workers';
import {ROOM_SCHEMA} from '../db/schema';
import {affordableLimit,calculateStartingBudget,hashSeed,openingPrice,passIsSafe,ratingLevel,RATING_TIERS,seededRandom,shuffleSeeded,type Era,type Footballer,type Manager,type PoolSourceEntry,type QualityMode,type RatingTier,type Slot} from './game-engine';
import generated from '../app/data/auction-pool.generated.json';

export type RoomMember={id:string;name:string;role:'manager'|'spectator';approved:boolean};
export type RoomSettings={era:Era;quality:QualityMode;revealRatings:boolean;selectedTiers:RatingTier[]};
export type RoomState={code:string;status:'lobby'|'auction'|'results';settings:RoomSettings;members:RoomMember[];createdAt:number;game?:{managers:Manager[];pool:Footballer[];index:number;bid:number;leader:number|null;passed:number[];activeTurn:number|null;paused:boolean;deadline:number|null;feed:string[]}};
type DBEnv={DB:D1Database}; const db=()=> (env as unknown as DBEnv).DB;
const slots:{key:Slot;label:string}[]=[{key:'GK',label:'Kaleci'},{key:'RB',label:'Sağ bek'},{key:'CB1',label:'Stoper'},{key:'CB2',label:'Stoper'},{key:'LB',label:'Sol bek'},{key:'DM',label:'Savunmacı merkez'},{key:'CM',label:'İki yönlü merkez'},{key:'AM',label:'Ofansif orta saha'},{key:'RW',label:'Sağ açık'},{key:'LW',label:'Sol açık'},{key:'ST',label:'Forvet'}];
let ready=false;async function ensure(){if(ready)return;for(const sql of ROOM_SCHEMA)await db().prepare(sql).run();ready=true}
export async function digest(v:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export const token=()=>crypto.randomUUID()+crypto.randomUUID();
export function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=crypto.getRandomValues(new Uint8Array(6));return [...bytes].map(x=>chars[x%chars.length]).join('')}
export async function cleanup(){await ensure();await db().prepare('DELETE FROM room_members WHERE room_code IN (SELECT code FROM rooms WHERE expires_at < ?)').bind(Date.now()).run();await db().prepare('DELETE FROM rooms WHERE expires_at < ?').bind(Date.now()).run()}
export async function createRoom(name:string,settings:RoomSettings){await cleanup();const roomCode=code(),hostToken=token(),memberToken=token(),memberId=crypto.randomUUID(),now=Date.now();const state:RoomState={code:roomCode,status:'lobby',settings,members:[{id:memberId,name,role:'manager',approved:true}],createdAt:now};await db().batch([db().prepare('INSERT INTO rooms VALUES (?,?,?,?,?,?)').bind(roomCode,await digest(hostToken),JSON.stringify(state),0,now,now+7*86400000),db().prepare('INSERT INTO room_members VALUES (?,?,?,?,?,?,?)').bind(roomCode,memberId,await digest(memberToken),name,'manager',1,now)]);return{code:roomCode,hostToken,memberToken,memberId}}
export async function joinRoom(roomCode:string,name:string,role:'manager'|'spectator'){await ensure();const row=await db().prepare('SELECT state_json FROM rooms WHERE code=? AND expires_at>?').bind(roomCode,Date.now()).first<{state_json:string}>();if(!row)throw new Error('Oda bulunamadı');const state=JSON.parse(row.state_json) as RoomState;if(state.status!=='lobby')throw new Error('Oyun başladı');if(state.members.some(m=>m.name.toLocaleLowerCase('tr')===name.toLocaleLowerCase('tr')))throw new Error('Bu isim kullanılıyor');if(role==='manager'&&state.members.filter(m=>m.role==='manager').length>=8)throw new Error('Menajer kontenjanı dolu');const memberId=crypto.randomUUID(),memberToken=token(),member={id:memberId,name,role,approved:false};state.members.push(member);await db().batch([db().prepare('UPDATE rooms SET state_json=?,revision=revision+1 WHERE code=?').bind(JSON.stringify(state),roomCode),db().prepare('INSERT INTO room_members VALUES (?,?,?,?,?,?,?)').bind(roomCode,memberId,await digest(memberToken),name,role,0,Date.now())]);return{code:roomCode,memberToken,memberId}}
export async function auth(roomCode:string,plain:string){await ensure();const hash=await digest(plain);const room=await db().prepare('SELECT state_json,revision,host_token_hash FROM rooms WHERE code=? AND expires_at>?').bind(roomCode,Date.now()).first<{state_json:string;revision:number;host_token_hash:string}>();if(!room)throw new Error('Oda bulunamadı');if(room.host_token_hash===hash){const member=await db().prepare("SELECT member_id,name,role,approved FROM room_members WHERE room_code=? AND role='manager' AND approved=1 ORDER BY rowid LIMIT 1").bind(roomCode).first<{member_id:string;name:string;role:'manager';approved:number}>();return{room,state:JSON.parse(room.state_json) as RoomState,isHost:true,member}}const member=await db().prepare('SELECT member_id,name,role,approved FROM room_members WHERE room_code=? AND token_hash=?').bind(roomCode,hash).first<{member_id:string;name:string;role:'manager'|'spectator';approved:number}>();if(!member)throw new Error('Yetkisiz bağlantı');await db().prepare('UPDATE room_members SET last_seen=? WHERE room_code=? AND member_id=?').bind(Date.now(),roomCode,member.member_id).run();return{room,state:JSON.parse(room.state_json) as RoomState,isHost:false,member}}
function buildPool(settings:RoomSettings,count:number,seed:string){const source=generated as unknown as Record<Era,Record<Slot,PoolSourceEntry[]>>,random=seededRandom(hashSeed(seed));return slots.flatMap(s=>{const candidates=(source[settings.era][s.key]||[]).filter(p=>settings.selectedTiers.includes(ratingLevel(p.rating)));const chosen=settings.quality==='best'?shuffleSeeded(candidates.slice(0,Math.max(24,(count+1)*3)),random).slice(0,count+1).sort((a,b)=>b.rating-a.rating):shuffleSeeded(candidates,random).slice(0,count+1);return chosen.map(p=>({id:`tm-${p.id}-${s.key}`,name:p.name,slot:s.key,role:s.label,rating:p.rating,price:p.price,nation:p.country.slice(0,3).toUpperCase(),club:p.club,image:p.image,clubLogo:p.clubLogo}))})}
export async function saveState(roomCode:string,state:RoomState,revision:number){const result=await db().prepare('UPDATE rooms SET state_json=?,revision=revision+1,expires_at=? WHERE code=? AND revision=?').bind(JSON.stringify(state),Date.now()+7*86400000,roomCode,revision).run();if(!result.meta.changes)throw new Error('Durum değişti; tekrar deneyin')}
function advanceUnsold(state:RoomState){const g=state.game;if(!g)return;let next=g.index+1;while(next<g.pool.length&&g.managers.every(m=>m.squad[g.pool[next].slot]))next++;if(next>=g.pool.length){state.status='results';g.deadline=null;return}g.index=next;g.bid=0;g.leader=null;g.passed=[];g.deadline=Date.now()+20000;const price=openingPrice(g.pool[next],g.managers);g.activeTurn=g.managers.findIndex(m=>!m.squad[g.pool[next].slot]&&affordableLimit(m)>=price);if(g.activeTurn<0)g.activeTurn=null}
export async function act(roomCode:string,plain:string,type:string,payload:Record<string,unknown>={}){const ctx=await auth(roomCode,plain);const {state}=ctx;const requireHost=()=>{if(!ctx.isHost)throw new Error('Yalnızca oda sahibi yapabilir')};
 if(type==='approve'){requireHost();const id=String(payload.memberId);const m=state.members.find(x=>x.id===id);if(!m)throw new Error('Katılımcı yok');m.approved=true;await db().prepare('UPDATE room_members SET approved=1 WHERE room_code=? AND member_id=?').bind(roomCode,id).run()}
 else if(type==='start'){requireHost();if(state.status!=='lobby')throw new Error('Oyun zaten başladı');const members=state.members.filter(m=>m.approved&&m.role==='manager');if(members.length<2)throw new Error('En az iki onaylı menajer gerekli');const pool=buildPool(state.settings,members.length,roomCode);const budget=calculateStartingBudget(pool,state.settings.quality);state.game={managers:members.map((m,i)=>({id:i,name:m.name,budget,spent:0,squad:{}})),pool,index:0,bid:0,leader:null,passed:[],activeTurn:0,paused:false,deadline:Date.now()+20000,feed:[`Oda ${roomCode}: açık artırma başladı.`]};state.status='auction'}
 else {if(state.status!=='auction'||!state.game)throw new Error('Açık artırma aktif değil');const g=state.game,lot=g.pool[g.index];if(!ctx.member||!ctx.member.approved||ctx.member.role!=='manager')throw new Error('Menajer yetkisi gerekli');const managerId=state.members.filter(m=>m.approved&&m.role==='manager').findIndex(m=>m.id===ctx.member?.member_id);if(managerId<0)throw new Error('Menajer bulunamadı');if(type==='bid'){if(g.paused||g.activeTurn!==managerId)throw new Error('Teklif sırası sizde değil');const offer=g.leader===null?openingPrice(lot,g.managers):g.bid+Number(payload.increment||5);const m=g.managers[managerId];if(m.squad[lot.slot]||g.passed.includes(managerId)||affordableLimit(m)<offer)throw new Error('Teklif geçersiz');g.bid=offer;g.leader=managerId;g.deadline=Date.now()+20000;g.feed=[`${m.name}, $${offer}M teklif verdi.`,...g.feed].slice(0,8);g.activeTurn=g.managers.findIndex((x,i)=>i!==managerId&&!g.passed.includes(i)&&!x.squad[lot.slot]&&affordableLimit(x)>=offer+5);if(g.activeTurn<0)g.activeTurn=null}
 else if(type==='pass'){if(g.paused||g.activeTurn!==managerId)throw new Error('Pas sırası sizde değil');if(g.leader===null&&!passIsSafe(g.pool,g.index,g.managers))throw new Error('Son güvenli adayda pas geçilemez');g.passed.push(managerId);g.deadline=Date.now()+20000;g.feed=[`${g.managers[managerId].name} pas geçti.`,...g.feed].slice(0,8);const offer=g.leader===null?openingPrice(lot,g.managers):g.bid+5;g.activeTurn=g.managers.findIndex((x,i)=>i!==g.leader&&!g.passed.includes(i)&&!x.squad[lot.slot]&&affordableLimit(x)>=offer);if(g.activeTurn<0)g.activeTurn=null}
 else if(type==='sell'){requireHost();if(g.leader===null||g.activeTurn!==null)throw new Error('Satış henüz bitirilemez');const win=g.managers[g.leader];win.squad[lot.slot]=lot;win.budget-=g.bid;win.spent+=g.bid;g.feed=[`${lot.name}, ${win.name} takımına $${g.bid}M karşılığında katıldı.`,...g.feed].slice(0,8);let next=g.index+1;while(next<g.pool.length&&g.managers.every(m=>m.squad[g.pool[next].slot]))next++;if(next>=g.pool.length){state.status='results';g.deadline=null}else{g.index=next;g.bid=0;g.leader=null;g.passed=[];g.deadline=Date.now()+20000;const price=openingPrice(g.pool[next],g.managers);g.activeTurn=g.managers.findIndex(m=>!m.squad[g.pool[next].slot]&&affordableLimit(m)>=price);if(g.activeTurn<0)g.activeTurn=null}}
 else if(type==='pause'){requireHost();g.paused=!g.paused;g.deadline=g.paused?null:Date.now()+20000}else throw new Error('Bilinmeyen işlem')}
 if(state.game&&state.status==='auction'&&state.game.activeTurn===null&&state.game.leader===null)advanceUnsold(state);
 await saveState(roomCode,state,ctx.room.revision);return state}
export async function publicRoom(roomCode:string,plain:string){const ctx=await auth(roomCode,plain),g=ctx.state.game;if(ctx.state.status==='auction'&&g&&g.deadline&&g.deadline<=Date.now()&&g.activeTurn!==null&&g.activeTurn>=0){const id=g.activeTurn,lot=g.pool[g.index],m=g.managers[id];if(g.leader===null&&!passIsSafe(g.pool,g.index,g.managers)){const offer=openingPrice(lot,g.managers);g.bid=offer;g.leader=id;g.feed=[`${m.name} süre sonunda ${offer}M açılış teklifini verdi.`,...g.feed].slice(0,8)}else{g.passed.push(id);g.feed=[`${m.name} süre sonunda pas geçti.`,...g.feed].slice(0,8)}const offer=g.leader===null?openingPrice(lot,g.managers):g.bid+5;const next=g.managers.findIndex((x,i)=>i!==g.leader&&!g.passed.includes(i)&&!x.squad[lot.slot]&&affordableLimit(x)>=offer);g.activeTurn=next<0?null:next;g.deadline=g.activeTurn===null?null:Date.now()+20000;if(g.activeTurn===null&&g.leader===null)advanceUnsold(ctx.state);try{await saveState(roomCode,ctx.state,ctx.room.revision);ctx.room.revision++}catch{} }return{state:ctx.state,revision:ctx.room.revision,isHost:ctx.isHost,memberId:ctx.member?.member_id||null,serverTime:Date.now()}}
export const defaultSettings:RoomSettings={era:'current',quality:'best',revealRatings:false,selectedTiers:RATING_TIERS};

