import {env} from 'cloudflare:workers';
import {ROOM_SCHEMA} from '../db/schema';
import {auctionGroupKey,auctionOpeningPrice,BENCH_SLOTS,calculateStartingBudget,canPlaceLotBid,fillMissingBenchSlot,fillMissingSlot,hashSeed,isCoach,lotFilled,mixedAuctionLots,positionAuctionLots,randomSlotOrder,ratingLevel,RATING_TIERS,seededRandom,type AuctionLot,type BenchSlot,type Era,type Footballer,type Manager,type PoolSourceEntry,type QualityMode,type RatingTier,type Slot} from './game-engine';
import {COACHES} from './coaches';
import generated from '../app/data/auction-pool.generated.json';

export type RoomMember={id:string;name:string;role:'manager'|'spectator';approved:boolean};
export type RoomSettings={era:Era;quality:QualityMode;revealRatings:boolean;selectedTiers:RatingTier[];auctionMode?:'live'|'manual';includeBench?:boolean};
export type RoomState={code:string;status:'lobby'|'auction'|'results';settings:RoomSettings;members:RoomMember[];createdAt:number;game?:{managers:Manager[];pool:AuctionLot[];index:number;bid:number;leader:number|null;passed:number[];activeTurn:number|null;paused:boolean;deadline:number|null;feed:string[]}};
type DBEnv={DB:D1Database}; const db=()=> (env as unknown as DBEnv).DB;
const slots:{key:Slot;label:string}[]=[{key:'GK',label:'Kaleci'},{key:'RB',label:'Sağ Bek'},{key:'CB1',label:'Stoper'},{key:'CB2',label:'Stoper'},{key:'LB',label:'Sol Bek'},{key:'DM',label:'Savunmacı Merkez Orta Saha'},{key:'CM',label:'İki Yönlü Merkez Orta Saha'},{key:'AM',label:'Ofansif Orta Saha'},{key:'RW',label:'Sağ Açık'},{key:'LW',label:'Sol Açık'},{key:'ST',label:'Forvet'}];
const sourceData=generated as unknown as Record<Era,Record<Slot,PoolSourceEntry[]>>;
let ready=false;async function ensure(){if(ready)return;for(const sql of ROOM_SCHEMA)await db().prepare(sql).run();ready=true}
export async function digest(v:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export const token=()=>crypto.randomUUID()+crypto.randomUUID();
export function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=crypto.getRandomValues(new Uint8Array(6));return [...bytes].map(x=>chars[x%chars.length]).join('')}
export async function cleanup(){await ensure();await db().prepare('DELETE FROM room_members WHERE room_code IN (SELECT code FROM rooms WHERE expires_at < ?)').bind(Date.now()).run();await db().prepare('DELETE FROM rooms WHERE expires_at < ?').bind(Date.now()).run()}
function normalizedSettings(settings:RoomSettings){const tiers=Array.isArray(settings.selectedTiers)?settings.selectedTiers.filter((tier):tier is RatingTier=>RATING_TIERS.includes(tier)):[];return{era:settings.era==='legends'?'legends':'current',quality:settings.quality==='all'?'all':'best',revealRatings:Boolean(settings.revealRatings),selectedTiers:tiers.length?tiers:RATING_TIERS,auctionMode:settings.auctionMode==='manual'?'manual':'live',includeBench:Boolean(settings.includeBench)} satisfies RoomSettings}
export async function createRoom(name:string,settings:RoomSettings){await cleanup();const roomCode=code(),hostToken=token(),memberToken=token(),memberId=crypto.randomUUID(),now=Date.now();const state:RoomState={code:roomCode,status:'lobby',settings:normalizedSettings(settings),members:[{id:memberId,name,role:'manager',approved:true}],createdAt:now};await db().batch([db().prepare('INSERT INTO rooms VALUES (?,?,?,?,?,?)').bind(roomCode,await digest(hostToken),JSON.stringify(state),0,now,now+7*86400000),db().prepare('INSERT INTO room_members VALUES (?,?,?,?,?,?,?)').bind(roomCode,memberId,await digest(memberToken),name,'manager',1,now)]);return{code:roomCode,hostToken,memberToken,memberId}}
export async function joinRoom(roomCode:string,name:string,role:'manager'|'spectator'){await ensure();const row=await db().prepare('SELECT state_json FROM rooms WHERE code=? AND expires_at>?').bind(roomCode,Date.now()).first<{state_json:string}>();if(!row)throw new Error('Oda bulunamadı');const state=JSON.parse(row.state_json) as RoomState;if(state.status!=='lobby')throw new Error('Oyun başladı');if(state.members.some(m=>m.name.toLocaleLowerCase('tr')===name.toLocaleLowerCase('tr')))throw new Error('Bu isim kullanılıyor');if(role==='manager'&&state.members.filter(m=>m.role==='manager').length>=8)throw new Error('Menajer kontenjanı dolu');const memberId=crypto.randomUUID(),memberToken=token(),member={id:memberId,name,role,approved:false};state.members.push(member);await db().batch([db().prepare('UPDATE rooms SET state_json=?,revision=revision+1 WHERE code=?').bind(JSON.stringify(state),roomCode),db().prepare('INSERT INTO room_members VALUES (?,?,?,?,?,?,?)').bind(roomCode,memberId,await digest(memberToken),name,role,0,Date.now())]);return{code:roomCode,memberToken,memberId}}
export async function auth(roomCode:string,plain:string){await ensure();const hash=await digest(plain);const room=await db().prepare('SELECT state_json,revision,host_token_hash FROM rooms WHERE code=? AND expires_at>?').bind(roomCode,Date.now()).first<{state_json:string;revision:number;host_token_hash:string}>();if(!room)throw new Error('Oda bulunamadı');if(room.host_token_hash===hash){const member=await db().prepare("SELECT member_id,name,role,approved FROM room_members WHERE room_code=? AND role='manager' AND approved=1 ORDER BY rowid LIMIT 1").bind(roomCode).first<{member_id:string;name:string;role:'manager';approved:number}>();return{room,state:JSON.parse(room.state_json) as RoomState,isHost:true,member}}const member=await db().prepare('SELECT member_id,name,role,approved FROM room_members WHERE room_code=? AND token_hash=?').bind(roomCode,hash).first<{member_id:string;name:string;role:'manager'|'spectator';approved:number}>();if(!member)throw new Error('Yetkisiz bağlantı');await db().prepare('UPDATE room_members SET last_seen=? WHERE room_code=? AND member_id=?').bind(Date.now(),roomCode,member.member_id).run();return{room,state:JSON.parse(room.state_json) as RoomState,isHost:false,member}}
async function recentLotIds(roomCode:string){const rows=await db().prepare("SELECT state_json FROM rooms WHERE code<>? AND json_extract(state_json,'$.game') IS NOT NULL ORDER BY created_at DESC LIMIT 12").bind(roomCode).all<{state_json:string}>(),ids=new Set<string>();for(const row of rows.results||[]){try{const state=JSON.parse(row.state_json) as RoomState;for(const lot of state.game?.pool||[])ids.add(lot.id)}catch{}}return ids}
function buildPool(settings:RoomSettings,count:number,seed:string,excluded:Set<string>){
 const random=seededRandom(hashSeed(`${seed}-${Date.now()}`));
 const footballers=randomSlotOrder(slots,random).flatMap(s=>{const candidates=(sourceData[settings.era][s.key]||[]).filter(p=>settings.selectedTiers.includes(ratingLevel(p.rating))).map(p=>({id:`tm-${p.id}-${s.key}`,name:p.name,slot:s.key,role:s.label,rating:p.rating,price:p.price,nation:p.country.slice(0,3).toUpperCase(),club:p.club,image:p.image,clubLogo:p.clubLogo} satisfies Footballer));const window=settings.quality==='best'?candidates.slice(0,Math.max(160,(count+1)*12)):candidates;return positionAuctionLots(window,excluded,count+1,random,s.key==='ST'?.72:.3,s.key==='ST'?3:2.5)});
 const starterNames=new Set(footballers.map(player=>player.name));
 const bench=settings.includeBench?randomSlotOrder(BENCH_SLOTS,random).flatMap(group=>{const candidates=group.sourceSlots.flatMap(slot=>(sourceData[settings.era][slot]||[]).filter(p=>settings.selectedTiers.includes(ratingLevel(p.rating))).map(p=>({id:`tm-${p.id}-${group.key}`,name:p.name,slot,benchSlot:group.key,role:group.label,rating:p.rating,price:p.price,nation:p.country.slice(0,3).toUpperCase(),club:p.club,image:p.image,clubLogo:p.clubLogo} satisfies Footballer))).filter(player=>!starterNames.has(player.name)).sort((a,b)=>b.rating-a.rating);const window=settings.quality==='best'?candidates.slice(0,Math.max(180,(count+1)*16)):candidates;return positionAuctionLots(window,excluded,count+1,random,.45,3)}):[];
 const coaches=mixedAuctionLots(COACHES,excluded,count+2,random);return[...footballers,...bench,...coaches] satisfies AuctionLot[]
}
export async function saveState(roomCode:string,state:RoomState,revision:number){const result=await db().prepare('UPDATE rooms SET state_json=?,revision=revision+1,expires_at=? WHERE code=? AND revision=?').bind(JSON.stringify(state),Date.now()+7*86400000,roomCode,revision).run();if(!result.meta.changes)throw new Error('Durum değişti; tekrar deneyin')}
const auctionMode=(state:RoomState)=>state.settings.auctionMode||'live';
function completeSlot(state:RoomState,slot:Slot){const g=state.game;if(!g)return;const role=slots.find(item=>item.key===slot)?.label||slot,result=fillMissingSlot(g.managers,slot,sourceData[state.settings.era][slot]||[],role,`${state.code}-${g.index}`,g.pool.map(lot=>lot.name));g.managers=result.managers;if(result.assignments.length)g.feed=[...result.assignments.map(item=>`${item.managerName}, ${slot} pozisyonunu boş bıraktığı için ${item.player.name} standart altı oyuncu olarak $${item.fee}M karşılığında otomatik atandı.`),...g.feed].slice(0,8)}
function completeBench(state:RoomState,benchSlot:BenchSlot){const g=state.game;if(!g)return;const group=BENCH_SLOTS.find(item=>item.key===benchSlot),candidates=(group?.sourceSlots||[]).flatMap(slot=>(sourceData[state.settings.era][slot]||[]).map(player=>({...player,slot}))),result=fillMissingBenchSlot(g.managers,benchSlot,candidates,group?.label||benchSlot,`${state.code}-${g.index}`,g.pool.map(lot=>lot.name));g.managers=result.managers;if(result.assignments.length)g.feed=[...result.assignments.map(item=>`${item.managerName}, ${group?.label||benchSlot} yuvasını boş bıraktığı için ${item.player.name} standart altı oyuncu olarak $${item.fee}M karşılığında otomatik atandı.`),...g.feed].slice(0,8)}
function completeGroup(state:RoomState,lot:AuctionLot){if(isCoach(lot))return;if(lot.benchSlot)completeBench(state,lot.benchSlot);else completeSlot(state,lot.slot)}
function completeAllSlots(state:RoomState){for(const item of slots)completeSlot(state,item.key);if(state.settings.includeBench)for(const item of BENCH_SLOTS)completeBench(state,item.key)}
function advanceLot(state:RoomState){const g=state.game;if(!g)return;const current=g.pool[g.index];let next=g.index+1;while(next<g.pool.length&&g.managers.every(m=>lotFilled(m,g.pool[next])))next++;if(!isCoach(current)&&(next>=g.pool.length||auctionGroupKey(g.pool[next])!==auctionGroupKey(current)))completeGroup(state,current);if(next>=g.pool.length){completeAllSlots(state);state.status='results';g.deadline=null;g.activeTurn=null;return}g.index=next;g.bid=0;g.leader=null;g.passed=[];if(auctionMode(state)==='manual'){g.activeTurn=0;g.deadline=null;return}const price=auctionOpeningPrice(g.pool[next],g.managers);g.activeTurn=g.managers.findIndex((m,i)=>canPlaceLotBid(m,g.pool[next],price,i));g.deadline=g.activeTurn===null||g.activeTurn<0?null:Date.now()+20000;if(g.activeTurn<0)g.activeTurn=null}
function awardCurrentLot(state:RoomState,managerIndex:number,amount:number){const g=state.game;if(!g)throw new Error('Açık artırma aktif değil');const lot=g.pool[g.index],winner=g.managers[managerIndex];if(!winner)throw new Error('Menajer bulunamadı');if(!canPlaceLotBid(winner,lot,amount,managerIndex))throw new Error('Tutar veya kadro uygun değil');if(isCoach(lot))winner.coach=lot;else if(lot.benchSlot)winner.bench={...(winner.bench||{}),[lot.benchSlot]:lot};else winner.squad[lot.slot]=lot;winner.budget-=amount;winner.spent+=amount;g.feed=[`${lot.name}, ${winner.name} takımına $${amount}M karşılığında katıldı.`,...g.feed].slice(0,8);advanceLot(state)}
export async function act(roomCode:string,plain:string,type:string,payload:Record<string,unknown>={}){const ctx=await auth(roomCode,plain);const {state}=ctx;const requireHost=()=>{if(!ctx.isHost)throw new Error('Yalnızca oda sahibi yapabilir')};
 if(type==='approve'){requireHost();const id=String(payload.memberId);const m=state.members.find(x=>x.id===id);if(!m)throw new Error('Katılımcı yok');m.approved=true;await db().prepare('UPDATE room_members SET approved=1 WHERE room_code=? AND member_id=?').bind(roomCode,id).run()}
 else if(type==='start'){requireHost();if(state.status!=='lobby')throw new Error('Oyun zaten başladı');const members=state.members.filter(m=>m.approved&&m.role==='manager');if(members.length<2)throw new Error('En az iki onaylı menajer gerekli');const pool=buildPool(state.settings,members.length,roomCode,await recentLotIds(roomCode));const budget=calculateStartingBudget(pool.filter((lot):lot is Footballer=>!isCoach(lot)&&!lot.benchSlot),state.settings.quality)+(state.settings.includeBench?250:0);const manual=auctionMode(state)==='manual';state.game={managers:members.map((m,i)=>({id:i,name:m.name,budget,spent:0,squad:{},...(state.settings.includeBench?{bench:{}}:{})})),pool,index:0,bid:0,leader:null,passed:[],activeTurn:0,paused:false,deadline:manual?null:Date.now()+20000,feed:[`Oda ${roomCode}: ${manual?'manuel ':' '}açık artırma başladı. ${state.settings.includeBench?'11 oyuncu + 4 yedek için kişi başı ekstra $250M eklendi.':'11 oyuncu modu.'}`]};state.status='auction'}
 else {if(state.status!=='auction'||!state.game)throw new Error('Açık artırma aktif değil');const g=state.game,lot=g.pool[g.index];if(!ctx.member||!ctx.member.approved||ctx.member.role!=='manager')throw new Error('Menajer yetkisi gerekli');const managerId=state.members.filter(m=>m.approved&&m.role==='manager').findIndex(m=>m.id===ctx.member?.member_id);if(managerId<0)throw new Error('Menajer bulunamadı');if(type==='bid'){if(auctionMode(state)!=='live')throw new Error('Manuel modda teklif verilmez');if(g.paused||g.activeTurn===null)throw new Error('Teklifler kapalı');if(g.leader===managerId)throw new Error('En yüksek teklif zaten sizde');const increment=Number(payload.increment||5);if(g.leader!==null&&![5,10,25].includes(increment))throw new Error('Teklif artışı geçersiz');const offer=g.leader===null?auctionOpeningPrice(lot,g.managers):g.bid+increment;const m=g.managers[managerId];if(!canPlaceLotBid(m,lot,offer,managerId,g.passed))throw new Error('Bütçe, kadro veya pas durumu teklife uygun değil');g.bid=offer;g.leader=managerId;g.deadline=Date.now()+20000;g.feed=[`${m.name}, $${offer}M teklif verdi.`,...g.feed].slice(0,8);g.activeTurn=managerId}
 else if(type==='pass'){if(auctionMode(state)!=='live')throw new Error('Manuel modda teklif verilmez');if(g.paused||g.activeTurn===null)throw new Error('Teklifler kapalı');if(g.passed.includes(managerId))throw new Error('Zaten pas geçtiniz');g.passed.push(managerId);g.feed=[`${g.managers[managerId].name} pas geçti.`,...g.feed].slice(0,8);const offer=g.leader===null?auctionOpeningPrice(lot,g.managers):g.bid+5;const available=g.managers.some((m,i)=>i!==g.leader&&canPlaceLotBid(m,lot,offer,i,g.passed));g.activeTurn=available?managerId:null;g.deadline=available?Date.now()+20000:null}
 else if(type==='sell'){requireHost();if(auctionMode(state)!=='live')throw new Error('Manuel modda oyuncu atama alanını kullanın');if(g.leader===null||g.activeTurn!==null)throw new Error('Önce teklifleri kapatın');awardCurrentLot(state,g.leader,g.bid)}
 else if(type==='close'){requireHost();if(auctionMode(state)!=='live')throw new Error('Bu işlem canlı moda aittir');g.activeTurn=null;g.deadline=null;g.feed=['Oda sahibi teklifleri kapattı.',...g.feed].slice(0,8)}
 else if(type==='reopen'){requireHost();if(auctionMode(state)!=='live')throw new Error('Bu işlem canlı moda aittir');g.activeTurn=managerId;g.deadline=Date.now()+20000;g.paused=false;g.feed=['Oda sahibi teklifleri yeniden açtı.',...g.feed].slice(0,8)}
 else if(type==='manualSell'){requireHost();if(auctionMode(state)!=='manual')throw new Error('Manuel mod etkin değil');const target=Number(payload.managerIndex),amount=Math.round(Number(payload.amount));if(!Number.isInteger(target)||!Number.isFinite(amount))throw new Error('Menajer ve tutar gerekli');awardCurrentLot(state,target,amount)}
 else if(type==='manualSkip'){requireHost();if(auctionMode(state)!=='manual')throw new Error('Manuel mod etkin değil');g.feed=[`${lot.name} satılmadı.`,...g.feed].slice(0,8);advanceLot(state)}
 else if(type==='pause'){requireHost();if(auctionMode(state)!=='live')throw new Error('Manuel modda duraklatma gerekmez');g.paused=!g.paused;g.deadline=g.paused?null:Date.now()+20000}else throw new Error('Bilinmeyen işlem')}
 if(state.game&&state.status==='auction'&&auctionMode(state)==='live'&&state.game.activeTurn===null&&state.game.leader===null)advanceLot(state);
 await saveState(roomCode,state,ctx.room.revision);return state}
export async function publicRoom(roomCode:string,plain:string){const ctx=await auth(roomCode,plain),g=ctx.state.game;if(ctx.state.status==='auction'&&g&&auctionMode(ctx.state)==='live'&&g.deadline&&g.deadline<=Date.now()&&g.activeTurn!==null){g.deadline=null;g.activeTurn=null;if(g.leader===null){const lot=g.pool[g.index];g.feed=[`${lot.name} için teklif gelmedi.`,...g.feed].slice(0,8);advanceLot(ctx.state)}else g.feed=['Süre doldu; teklif verme kapandı.',...g.feed].slice(0,8);try{await saveState(roomCode,ctx.state,ctx.room.revision);ctx.room.revision++}catch{} }return{state:ctx.state,revision:ctx.room.revision,isHost:ctx.isHost,memberId:ctx.member?.member_id||null,serverTime:Date.now()}}
export const defaultSettings:RoomSettings={era:'current',quality:'best',revealRatings:false,selectedTiers:RATING_TIERS,auctionMode:'live',includeBench:false};

